# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_dashboard_app', '0001_initial'),
        ('jobs_app', '0002_auto_20190802_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ManyToManyField(related_name='jobs', to='login_dashboard_app.User'),
        ),
    ]
