# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_dashboard_app', '0001_initial'),
        ('jobs_app', '0003_auto_20190802_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='login_dashboard_app.User'),
        ),
    ]
